version: '3'

services:
  ml-client:
    build: ./ml-client
    container_name: asl-model
    ports:
      - "5001:5001"
    volumes:
      - ./ml-client:/app
    environment:
      - FLASK_APP=asl_model.py
      - FLASK_ENV=development
    networks:
      - app-network

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5003:5003"
    volumes:
      - ./web-app:/app
    environment:
      - FLASK_APP=web_app.py
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      mongodb:
        condition: service_healthy
      ml-client:
        condition: service_started
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:


    