version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - asl_network

  web-app:
    build: ./web-app
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - PORT=5001
    depends_on:
      - mongodb
    volumes:
      - ./web-app:/app
    networks:
      - asl_network

networks:
  asl_network:
    driver: bridge

volumes:
  mongodb_data: 
