version: '3'


services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ml-client:
    build:
      context: ./ml-client
    container_name: asl-model #CONTAINER NAME IS asl-model
    ports:
      - "5001:5001"
    restart: unless-stopped


  web-app:
    build:
      context: ./web-app
    ports:
      - "5003:5003"
    environment:
      - PYTHONUNBUFFERED=1
    # Using 'extra_hosts' to add a host mapping for host.docker.internal
    # This ensures compatibility across Docker versions 
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    
    depends_on:
      - ml-client
    restart: unless-stopped 

volumes:
  mongodb_data:
    {}
    