name: ML Client - CI

on:
  push:
    paths:
      - 'ml_client/**'
      - '.github/workflows/ml-client.yml'
      - 'README.md'
  pull_request:
    paths:
      - 'ml_client/**'
      - '.github/workflows/ml-client.yml'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ml_client
        run: |
          pip install pipenv
          pipenv install --dev --python $(which python)

      - name: Run tests
        working-directory: ml_client
        run: |
          pipenv run pytest tests --cov=asl_model --cov-report=term-missing
