name: ML Client - CI

on:
  push:
    paths:
      - 'ml-client/**'
      - '.github/workflows/ml-client.yml'
      - 'README.md'
  pull_request:
    paths:
      - 'ml-client/**'
      - '.github/workflows/ml-client.yml'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd ml-client
          pip install pipenv
          pipenv install --dev

      - name: Run tests
        run: |
          cd ml-client
          pipenv run pytest --cov=. --cov-report=term-missing
