name: ML Client - CI

on:
  push:
    paths:
      - 'ml_client/**'
      - '.github/workflows/ml-client.yml'
      - 'README.md'
  pull_request:
    paths:
      - 'ml_client/**'
      - '.github/workflows/ml-client.yml'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx

      - name: Install dependencies
        working-directory: ml_client
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        working-directory: ml_client
        run: |
          python -m pytest tests/ --cov=. --cov-report=term-missing --cov-fail-under=80
