name: Web App - CI

on:
  push:
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'
      - 'README.md'
  pull_request:
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        working-directory: web-app
        run: |
          pip install pipenv
          pipenv install --dev --python $(which python)

      - name: Run tests
        working-directory: web-app
        run: |
          pipenv run pytest tests --cov=. --cov-report=term-missing


