name: Web App - CI

on:
  push:
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'
  pull_request:
    paths:
      - 'web-app/**'
      - '.github/workflows/web-app.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        working-directory: web-app
        run: |
          pipenv install --dev
          pipenv install pytest-cov 

      - name: Run tests
        working-directory: web-app
        run: pipenv run pytest tests --cov=web_app --cov-report=term-missing



