name: Web App - CI

on:
  push:
    paths:
      - 'web-app/**'
  pull_request:
    paths:
      - 'web-app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd web-app
          pip install pipenv
          pipenv install --dev

      - name: Run tests
        run: |
          cd web-app
          pipenv run pytest --cov=. --cov-report=term-missing
