name: Web App - CI

on:
  push:
    paths:
      - 'web-app/**'
  pull_request:
    paths:
      - 'web-app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd web-app
          pipenv install --dev --python 3.8

      - name: Run tests
        run: |
          cd web-app
          pipenv run pytest --cov=. --cov-report=term-missing
